name: Terraform
on: push

jobs:
  main:
    name: Validate (Provider v${{ matrix.cloudflare_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloudflare_version: ['3', '4', '5']
    steps:
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/checkout@v2
      - name: Init test directory (v${{ matrix.cloudflare_version }})
        run: terraform init
        working-directory: test-v${{ matrix.cloudflare_version }}
      - name: Validate test directory (v${{ matrix.cloudflare_version }})
        run: terraform validate
        working-directory: test-v${{ matrix.cloudflare_version }}

